/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RouteImport } from './routes/route'
import { Route as TenantIndexImport } from './routes/$tenant/index'
import { Route as TenantVendorsIndexImport } from './routes/$tenant/vendors/index'
import { Route as TenantUsersIndexImport } from './routes/$tenant/users/index'
import { Route as TenantTenantsIndexImport } from './routes/$tenant/tenants/index'
import { Route as TenantRolesIndexImport } from './routes/$tenant/roles/index'
import { Route as TenantProductsIndexImport } from './routes/$tenant/products/index'
import { Route as TenantLoansIndexImport } from './routes/$tenant/loans/index'
import { Route as TenantJobTitlesIndexImport } from './routes/$tenant/jobTitles/index'
import { Route as TenantEmployeesIndexImport } from './routes/$tenant/employees/index'
import { Route as TenantDepartmentsIndexImport } from './routes/$tenant/departments/index'
import { Route as TenantCustomersIndexImport } from './routes/$tenant/customers/index'
import { Route as TenantVendorsAddImport } from './routes/$tenant/vendors/add'
import { Route as TenantVendorsIdImport } from './routes/$tenant/vendors/$id'
import { Route as TenantUsersApprovedImport } from './routes/$tenant/users/approved'
import { Route as TenantUsersAddImport } from './routes/$tenant/users/add'
import { Route as TenantUsersIdImport } from './routes/$tenant/users/$id'
import { Route as TenantTenantsAddImport } from './routes/$tenant/tenants/add'
import { Route as TenantTenantsIdImport } from './routes/$tenant/tenants/$id'
import { Route as TenantRolesAddImport } from './routes/$tenant/roles/add'
import { Route as TenantRolesIdImport } from './routes/$tenant/roles/$id'
import { Route as TenantProductsAddImport } from './routes/$tenant/products/add'
import { Route as TenantProductsIdImport } from './routes/$tenant/products/$id'
import { Route as TenantLoansAddImport } from './routes/$tenant/loans/add'
import { Route as TenantLoansIdImport } from './routes/$tenant/loans/$id'
import { Route as TenantJobTitlesAddImport } from './routes/$tenant/jobTitles/add'
import { Route as TenantJobTitlesIdImport } from './routes/$tenant/jobTitles/$id'
import { Route as TenantEmployeesIdImport } from './routes/$tenant/employees/$id'
import { Route as TenantDepartmentsAddImport } from './routes/$tenant/departments/add'
import { Route as TenantDepartmentsIdImport } from './routes/$tenant/departments/$id'
import { Route as TenantCustomersAddImport } from './routes/$tenant/customers/add'
import { Route as TenantCustomersIdImport } from './routes/$tenant/customers/$id'
import { Route as TenantVendorsEditIdImport } from './routes/$tenant/vendors/edit.$id'
import { Route as TenantUsersEditIdImport } from './routes/$tenant/users/edit.$id'
import { Route as TenantTenantsEditIdImport } from './routes/$tenant/tenants/edit.$id'
import { Route as TenantRolesEditIdImport } from './routes/$tenant/roles/edit.$id'
import { Route as TenantProductsEditIdImport } from './routes/$tenant/products/edit.$id'
import { Route as TenantLoansEditIdImport } from './routes/$tenant/loans/edit.$id'
import { Route as TenantJobTitlesEditIdImport } from './routes/$tenant/jobTitles/edit.$id'
import { Route as TenantDepartmentsEditIdImport } from './routes/$tenant/departments/edit.$id'
import { Route as TenantCustomersEditIdImport } from './routes/$tenant/customers/edit.$id'
import { Route as TenantLoansPayIdRouteImport } from './routes/$tenant/loans/pay/$id/route'
import { Route as TenantEmployeesPayIdRouteImport } from './routes/$tenant/employees/pay/$id/route'
import { Route as TenantLoansPayIdAddImport } from './routes/$tenant/loans/pay/$id/add'
import { Route as TenantEmployeesPayIdAddImport } from './routes/$tenant/employees/pay/$id/add'
import { Route as TenantLoansPayIdEditPaymentIdImport } from './routes/$tenant/loans/pay/$id/edit.$paymentId'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const AuthLazyImport = createFileRoute('/_auth')()
const LearnMoreRouteLazyImport = createFileRoute('/learn-more')()
const ApprovalRouteLazyImport = createFileRoute('/approval')()
const TenantRouteLazyImport = createFileRoute('/$tenant')()
const AuthRegisterRouteLazyImport = createFileRoute('/_auth/register')()
const AuthLoginRouteLazyImport = createFileRoute('/_auth/login')()
const AuthForgotPasswordRouteLazyImport = createFileRoute(
  '/_auth/forgot-password',
)()
const AuthCompanySelectRouteLazyImport = createFileRoute(
  '/_auth/company-select',
)()
const TenantVendorsRouteLazyImport = createFileRoute('/$tenant/vendors')()
const TenantUsersRouteLazyImport = createFileRoute('/$tenant/users')()
const TenantTenantsRouteLazyImport = createFileRoute('/$tenant/tenants')()
const TenantRolesRouteLazyImport = createFileRoute('/$tenant/roles')()
const TenantProductsRouteLazyImport = createFileRoute('/$tenant/products')()
const TenantLoansRouteLazyImport = createFileRoute('/$tenant/loans')()
const TenantJobTitlesRouteLazyImport = createFileRoute('/$tenant/jobTitles')()
const TenantHamadaRouteLazyImport = createFileRoute('/$tenant/hamada')()
const TenantEmployeesRouteLazyImport = createFileRoute('/$tenant/employees')()
const TenantDepartmentsRouteLazyImport = createFileRoute(
  '/$tenant/departments',
)()
const TenantCustomersRouteLazyImport = createFileRoute('/$tenant/customers')()
const AuthResetPasswordTokenLazyImport = createFileRoute(
  '/_auth/reset-password/$token',
)()
const TenantEmployeesAddLazyImport = createFileRoute('/$tenant/employees/add')()
const AuthRegisterUuidRouteLazyImport = createFileRoute(
  '/_auth/register/$uuid',
)()
const TenantEmployeesEditIdLazyImport = createFileRoute(
  '/$tenant/employees/edit/$id',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthLazyRoute = AuthLazyImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_auth.lazy').then((d) => d.Route))

const LearnMoreRouteLazyRoute = LearnMoreRouteLazyImport.update({
  path: '/learn-more',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/learn-more/route.lazy').then((d) => d.Route),
)

const ApprovalRouteLazyRoute = ApprovalRouteLazyImport.update({
  path: '/approval',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/approval/route.lazy').then((d) => d.Route),
)

const TenantRouteLazyRoute = TenantRouteLazyImport.update({
  path: '/$tenant',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$tenant/route.lazy').then((d) => d.Route))

const RouteRoute = RouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TenantIndexRoute = TenantIndexImport.update({
  path: '/',
  getParentRoute: () => TenantRouteLazyRoute,
} as any)

const AuthRegisterRouteLazyRoute = AuthRegisterRouteLazyImport.update({
  path: '/register',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/_auth/register/route.lazy').then((d) => d.Route),
)

const AuthLoginRouteLazyRoute = AuthLoginRouteLazyImport.update({
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/_auth/login/route.lazy').then((d) => d.Route),
)

const AuthForgotPasswordRouteLazyRoute =
  AuthForgotPasswordRouteLazyImport.update({
    path: '/forgot-password',
    getParentRoute: () => AuthLazyRoute,
  } as any).lazy(() =>
    import('./routes/_auth/forgot-password/route.lazy').then((d) => d.Route),
  )

const AuthCompanySelectRouteLazyRoute = AuthCompanySelectRouteLazyImport.update(
  {
    path: '/company-select',
    getParentRoute: () => AuthLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/_auth/company-select/route.lazy').then((d) => d.Route),
)

const TenantVendorsRouteLazyRoute = TenantVendorsRouteLazyImport.update({
  path: '/vendors',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/vendors/route.lazy').then((d) => d.Route),
)

const TenantUsersRouteLazyRoute = TenantUsersRouteLazyImport.update({
  path: '/users',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/users/route.lazy').then((d) => d.Route),
)

const TenantTenantsRouteLazyRoute = TenantTenantsRouteLazyImport.update({
  path: '/tenants',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/tenants/route.lazy').then((d) => d.Route),
)

const TenantRolesRouteLazyRoute = TenantRolesRouteLazyImport.update({
  path: '/roles',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/roles/route.lazy').then((d) => d.Route),
)

const TenantProductsRouteLazyRoute = TenantProductsRouteLazyImport.update({
  path: '/products',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/products/route.lazy').then((d) => d.Route),
)

const TenantLoansRouteLazyRoute = TenantLoansRouteLazyImport.update({
  path: '/loans',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/loans/route.lazy').then((d) => d.Route),
)

const TenantJobTitlesRouteLazyRoute = TenantJobTitlesRouteLazyImport.update({
  path: '/jobTitles',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/jobTitles/route.lazy').then((d) => d.Route),
)

const TenantHamadaRouteLazyRoute = TenantHamadaRouteLazyImport.update({
  path: '/hamada',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/hamada/route.lazy').then((d) => d.Route),
)

const TenantEmployeesRouteLazyRoute = TenantEmployeesRouteLazyImport.update({
  path: '/employees',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/employees/route.lazy').then((d) => d.Route),
)

const TenantDepartmentsRouteLazyRoute = TenantDepartmentsRouteLazyImport.update(
  {
    path: '/departments',
    getParentRoute: () => TenantRouteLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/$tenant/departments/route.lazy').then((d) => d.Route),
)

const TenantCustomersRouteLazyRoute = TenantCustomersRouteLazyImport.update({
  path: '/customers',
  getParentRoute: () => TenantRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/customers/route.lazy').then((d) => d.Route),
)

const TenantVendorsIndexRoute = TenantVendorsIndexImport.update({
  path: '/',
  getParentRoute: () => TenantVendorsRouteLazyRoute,
} as any)

const TenantUsersIndexRoute = TenantUsersIndexImport.update({
  path: '/',
  getParentRoute: () => TenantUsersRouteLazyRoute,
} as any)

const TenantTenantsIndexRoute = TenantTenantsIndexImport.update({
  path: '/',
  getParentRoute: () => TenantTenantsRouteLazyRoute,
} as any)

const TenantRolesIndexRoute = TenantRolesIndexImport.update({
  path: '/',
  getParentRoute: () => TenantRolesRouteLazyRoute,
} as any)

const TenantProductsIndexRoute = TenantProductsIndexImport.update({
  path: '/',
  getParentRoute: () => TenantProductsRouteLazyRoute,
} as any)

const TenantLoansIndexRoute = TenantLoansIndexImport.update({
  path: '/',
  getParentRoute: () => TenantLoansRouteLazyRoute,
} as any)

const TenantJobTitlesIndexRoute = TenantJobTitlesIndexImport.update({
  path: '/',
  getParentRoute: () => TenantJobTitlesRouteLazyRoute,
} as any)

const TenantEmployeesIndexRoute = TenantEmployeesIndexImport.update({
  path: '/',
  getParentRoute: () => TenantEmployeesRouteLazyRoute,
} as any)

const TenantDepartmentsIndexRoute = TenantDepartmentsIndexImport.update({
  path: '/',
  getParentRoute: () => TenantDepartmentsRouteLazyRoute,
} as any)

const TenantCustomersIndexRoute = TenantCustomersIndexImport.update({
  path: '/',
  getParentRoute: () => TenantCustomersRouteLazyRoute,
} as any)

const AuthResetPasswordTokenLazyRoute = AuthResetPasswordTokenLazyImport.update(
  {
    path: '/reset-password/$token',
    getParentRoute: () => AuthLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/_auth/reset-password/$token.lazy').then((d) => d.Route),
)

const TenantEmployeesAddLazyRoute = TenantEmployeesAddLazyImport.update({
  path: '/add',
  getParentRoute: () => TenantEmployeesRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/employees/add.lazy').then((d) => d.Route),
)

const AuthRegisterUuidRouteLazyRoute = AuthRegisterUuidRouteLazyImport.update({
  path: '/$uuid',
  getParentRoute: () => AuthRegisterRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_auth/register/$uuid/route.lazy').then((d) => d.Route),
)

const TenantVendorsAddRoute = TenantVendorsAddImport.update({
  path: '/add',
  getParentRoute: () => TenantVendorsRouteLazyRoute,
} as any)

const TenantVendorsIdRoute = TenantVendorsIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantVendorsRouteLazyRoute,
} as any)

const TenantUsersApprovedRoute = TenantUsersApprovedImport.update({
  path: '/approved',
  getParentRoute: () => TenantUsersRouteLazyRoute,
} as any)

const TenantUsersAddRoute = TenantUsersAddImport.update({
  path: '/add',
  getParentRoute: () => TenantUsersRouteLazyRoute,
} as any)

const TenantUsersIdRoute = TenantUsersIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantUsersRouteLazyRoute,
} as any)

const TenantTenantsAddRoute = TenantTenantsAddImport.update({
  path: '/add',
  getParentRoute: () => TenantTenantsRouteLazyRoute,
} as any)

const TenantTenantsIdRoute = TenantTenantsIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantTenantsRouteLazyRoute,
} as any)

const TenantRolesAddRoute = TenantRolesAddImport.update({
  path: '/add',
  getParentRoute: () => TenantRolesRouteLazyRoute,
} as any)

const TenantRolesIdRoute = TenantRolesIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantRolesRouteLazyRoute,
} as any)

const TenantProductsAddRoute = TenantProductsAddImport.update({
  path: '/add',
  getParentRoute: () => TenantProductsRouteLazyRoute,
} as any)

const TenantProductsIdRoute = TenantProductsIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantProductsRouteLazyRoute,
} as any)

const TenantLoansAddRoute = TenantLoansAddImport.update({
  path: '/add',
  getParentRoute: () => TenantLoansRouteLazyRoute,
} as any)

const TenantLoansIdRoute = TenantLoansIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantLoansRouteLazyRoute,
} as any)

const TenantJobTitlesAddRoute = TenantJobTitlesAddImport.update({
  path: '/add',
  getParentRoute: () => TenantJobTitlesRouteLazyRoute,
} as any)

const TenantJobTitlesIdRoute = TenantJobTitlesIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantJobTitlesRouteLazyRoute,
} as any)

const TenantEmployeesIdRoute = TenantEmployeesIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantEmployeesRouteLazyRoute,
} as any)

const TenantDepartmentsAddRoute = TenantDepartmentsAddImport.update({
  path: '/add',
  getParentRoute: () => TenantDepartmentsRouteLazyRoute,
} as any)

const TenantDepartmentsIdRoute = TenantDepartmentsIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantDepartmentsRouteLazyRoute,
} as any)

const TenantCustomersAddRoute = TenantCustomersAddImport.update({
  path: '/add',
  getParentRoute: () => TenantCustomersRouteLazyRoute,
} as any)

const TenantCustomersIdRoute = TenantCustomersIdImport.update({
  path: '/$id',
  getParentRoute: () => TenantCustomersRouteLazyRoute,
} as any)

const TenantEmployeesEditIdLazyRoute = TenantEmployeesEditIdLazyImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantEmployeesRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/$tenant/employees/edit.$id.lazy').then((d) => d.Route),
)

const TenantVendorsEditIdRoute = TenantVendorsEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantVendorsRouteLazyRoute,
} as any)

const TenantUsersEditIdRoute = TenantUsersEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantUsersRouteLazyRoute,
} as any)

const TenantTenantsEditIdRoute = TenantTenantsEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantTenantsRouteLazyRoute,
} as any)

const TenantRolesEditIdRoute = TenantRolesEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantRolesRouteLazyRoute,
} as any)

const TenantProductsEditIdRoute = TenantProductsEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantProductsRouteLazyRoute,
} as any)

const TenantLoansEditIdRoute = TenantLoansEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantLoansRouteLazyRoute,
} as any)

const TenantJobTitlesEditIdRoute = TenantJobTitlesEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantJobTitlesRouteLazyRoute,
} as any)

const TenantDepartmentsEditIdRoute = TenantDepartmentsEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantDepartmentsRouteLazyRoute,
} as any)

const TenantCustomersEditIdRoute = TenantCustomersEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => TenantCustomersRouteLazyRoute,
} as any)

const TenantLoansPayIdRouteRoute = TenantLoansPayIdRouteImport.update({
  path: '/pay/$id',
  getParentRoute: () => TenantLoansRouteLazyRoute,
} as any)

const TenantEmployeesPayIdRouteRoute = TenantEmployeesPayIdRouteImport.update({
  path: '/pay/$id',
  getParentRoute: () => TenantEmployeesRouteLazyRoute,
} as any)

const TenantLoansPayIdAddRoute = TenantLoansPayIdAddImport.update({
  path: '/add',
  getParentRoute: () => TenantLoansPayIdRouteRoute,
} as any)

const TenantEmployeesPayIdAddRoute = TenantEmployeesPayIdAddImport.update({
  path: '/add',
  getParentRoute: () => TenantEmployeesPayIdRouteRoute,
} as any)

const TenantLoansPayIdEditPaymentIdRoute =
  TenantLoansPayIdEditPaymentIdImport.update({
    path: '/edit/$paymentId',
    getParentRoute: () => TenantLoansPayIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRoute
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/learn-more': {
      id: '/learn-more'
      path: '/learn-more'
      fullPath: '/learn-more'
      preLoaderRoute: typeof LearnMoreRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/$tenant/customers': {
      id: '/$tenant/customers'
      path: '/customers'
      fullPath: '/$tenant/customers'
      preLoaderRoute: typeof TenantCustomersRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/departments': {
      id: '/$tenant/departments'
      path: '/departments'
      fullPath: '/$tenant/departments'
      preLoaderRoute: typeof TenantDepartmentsRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/employees': {
      id: '/$tenant/employees'
      path: '/employees'
      fullPath: '/$tenant/employees'
      preLoaderRoute: typeof TenantEmployeesRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/hamada': {
      id: '/$tenant/hamada'
      path: '/hamada'
      fullPath: '/$tenant/hamada'
      preLoaderRoute: typeof TenantHamadaRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/jobTitles': {
      id: '/$tenant/jobTitles'
      path: '/jobTitles'
      fullPath: '/$tenant/jobTitles'
      preLoaderRoute: typeof TenantJobTitlesRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/loans': {
      id: '/$tenant/loans'
      path: '/loans'
      fullPath: '/$tenant/loans'
      preLoaderRoute: typeof TenantLoansRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/products': {
      id: '/$tenant/products'
      path: '/products'
      fullPath: '/$tenant/products'
      preLoaderRoute: typeof TenantProductsRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/roles': {
      id: '/$tenant/roles'
      path: '/roles'
      fullPath: '/$tenant/roles'
      preLoaderRoute: typeof TenantRolesRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/tenants': {
      id: '/$tenant/tenants'
      path: '/tenants'
      fullPath: '/$tenant/tenants'
      preLoaderRoute: typeof TenantTenantsRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/users': {
      id: '/$tenant/users'
      path: '/users'
      fullPath: '/$tenant/users'
      preLoaderRoute: typeof TenantUsersRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/vendors': {
      id: '/$tenant/vendors'
      path: '/vendors'
      fullPath: '/$tenant/vendors'
      preLoaderRoute: typeof TenantVendorsRouteLazyImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/_auth/company-select': {
      id: '/_auth/company-select'
      path: '/company-select'
      fullPath: '/company-select'
      preLoaderRoute: typeof AuthCompanySelectRouteLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexImport
      parentRoute: typeof TenantRouteLazyImport
    }
    '/$tenant/customers/$id': {
      id: '/$tenant/customers/$id'
      path: '/$id'
      fullPath: '/$tenant/customers/$id'
      preLoaderRoute: typeof TenantCustomersIdImport
      parentRoute: typeof TenantCustomersRouteLazyImport
    }
    '/$tenant/customers/add': {
      id: '/$tenant/customers/add'
      path: '/add'
      fullPath: '/$tenant/customers/add'
      preLoaderRoute: typeof TenantCustomersAddImport
      parentRoute: typeof TenantCustomersRouteLazyImport
    }
    '/$tenant/departments/$id': {
      id: '/$tenant/departments/$id'
      path: '/$id'
      fullPath: '/$tenant/departments/$id'
      preLoaderRoute: typeof TenantDepartmentsIdImport
      parentRoute: typeof TenantDepartmentsRouteLazyImport
    }
    '/$tenant/departments/add': {
      id: '/$tenant/departments/add'
      path: '/add'
      fullPath: '/$tenant/departments/add'
      preLoaderRoute: typeof TenantDepartmentsAddImport
      parentRoute: typeof TenantDepartmentsRouteLazyImport
    }
    '/$tenant/employees/$id': {
      id: '/$tenant/employees/$id'
      path: '/$id'
      fullPath: '/$tenant/employees/$id'
      preLoaderRoute: typeof TenantEmployeesIdImport
      parentRoute: typeof TenantEmployeesRouteLazyImport
    }
    '/$tenant/jobTitles/$id': {
      id: '/$tenant/jobTitles/$id'
      path: '/$id'
      fullPath: '/$tenant/jobTitles/$id'
      preLoaderRoute: typeof TenantJobTitlesIdImport
      parentRoute: typeof TenantJobTitlesRouteLazyImport
    }
    '/$tenant/jobTitles/add': {
      id: '/$tenant/jobTitles/add'
      path: '/add'
      fullPath: '/$tenant/jobTitles/add'
      preLoaderRoute: typeof TenantJobTitlesAddImport
      parentRoute: typeof TenantJobTitlesRouteLazyImport
    }
    '/$tenant/loans/$id': {
      id: '/$tenant/loans/$id'
      path: '/$id'
      fullPath: '/$tenant/loans/$id'
      preLoaderRoute: typeof TenantLoansIdImport
      parentRoute: typeof TenantLoansRouteLazyImport
    }
    '/$tenant/loans/add': {
      id: '/$tenant/loans/add'
      path: '/add'
      fullPath: '/$tenant/loans/add'
      preLoaderRoute: typeof TenantLoansAddImport
      parentRoute: typeof TenantLoansRouteLazyImport
    }
    '/$tenant/products/$id': {
      id: '/$tenant/products/$id'
      path: '/$id'
      fullPath: '/$tenant/products/$id'
      preLoaderRoute: typeof TenantProductsIdImport
      parentRoute: typeof TenantProductsRouteLazyImport
    }
    '/$tenant/products/add': {
      id: '/$tenant/products/add'
      path: '/add'
      fullPath: '/$tenant/products/add'
      preLoaderRoute: typeof TenantProductsAddImport
      parentRoute: typeof TenantProductsRouteLazyImport
    }
    '/$tenant/roles/$id': {
      id: '/$tenant/roles/$id'
      path: '/$id'
      fullPath: '/$tenant/roles/$id'
      preLoaderRoute: typeof TenantRolesIdImport
      parentRoute: typeof TenantRolesRouteLazyImport
    }
    '/$tenant/roles/add': {
      id: '/$tenant/roles/add'
      path: '/add'
      fullPath: '/$tenant/roles/add'
      preLoaderRoute: typeof TenantRolesAddImport
      parentRoute: typeof TenantRolesRouteLazyImport
    }
    '/$tenant/tenants/$id': {
      id: '/$tenant/tenants/$id'
      path: '/$id'
      fullPath: '/$tenant/tenants/$id'
      preLoaderRoute: typeof TenantTenantsIdImport
      parentRoute: typeof TenantTenantsRouteLazyImport
    }
    '/$tenant/tenants/add': {
      id: '/$tenant/tenants/add'
      path: '/add'
      fullPath: '/$tenant/tenants/add'
      preLoaderRoute: typeof TenantTenantsAddImport
      parentRoute: typeof TenantTenantsRouteLazyImport
    }
    '/$tenant/users/$id': {
      id: '/$tenant/users/$id'
      path: '/$id'
      fullPath: '/$tenant/users/$id'
      preLoaderRoute: typeof TenantUsersIdImport
      parentRoute: typeof TenantUsersRouteLazyImport
    }
    '/$tenant/users/add': {
      id: '/$tenant/users/add'
      path: '/add'
      fullPath: '/$tenant/users/add'
      preLoaderRoute: typeof TenantUsersAddImport
      parentRoute: typeof TenantUsersRouteLazyImport
    }
    '/$tenant/users/approved': {
      id: '/$tenant/users/approved'
      path: '/approved'
      fullPath: '/$tenant/users/approved'
      preLoaderRoute: typeof TenantUsersApprovedImport
      parentRoute: typeof TenantUsersRouteLazyImport
    }
    '/$tenant/vendors/$id': {
      id: '/$tenant/vendors/$id'
      path: '/$id'
      fullPath: '/$tenant/vendors/$id'
      preLoaderRoute: typeof TenantVendorsIdImport
      parentRoute: typeof TenantVendorsRouteLazyImport
    }
    '/$tenant/vendors/add': {
      id: '/$tenant/vendors/add'
      path: '/add'
      fullPath: '/$tenant/vendors/add'
      preLoaderRoute: typeof TenantVendorsAddImport
      parentRoute: typeof TenantVendorsRouteLazyImport
    }
    '/_auth/register/$uuid': {
      id: '/_auth/register/$uuid'
      path: '/$uuid'
      fullPath: '/register/$uuid'
      preLoaderRoute: typeof AuthRegisterUuidRouteLazyImport
      parentRoute: typeof AuthRegisterRouteLazyImport
    }
    '/$tenant/employees/add': {
      id: '/$tenant/employees/add'
      path: '/add'
      fullPath: '/$tenant/employees/add'
      preLoaderRoute: typeof TenantEmployeesAddLazyImport
      parentRoute: typeof TenantEmployeesRouteLazyImport
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/$tenant/customers/': {
      id: '/$tenant/customers/'
      path: '/'
      fullPath: '/$tenant/customers/'
      preLoaderRoute: typeof TenantCustomersIndexImport
      parentRoute: typeof TenantCustomersRouteLazyImport
    }
    '/$tenant/departments/': {
      id: '/$tenant/departments/'
      path: '/'
      fullPath: '/$tenant/departments/'
      preLoaderRoute: typeof TenantDepartmentsIndexImport
      parentRoute: typeof TenantDepartmentsRouteLazyImport
    }
    '/$tenant/employees/': {
      id: '/$tenant/employees/'
      path: '/'
      fullPath: '/$tenant/employees/'
      preLoaderRoute: typeof TenantEmployeesIndexImport
      parentRoute: typeof TenantEmployeesRouteLazyImport
    }
    '/$tenant/jobTitles/': {
      id: '/$tenant/jobTitles/'
      path: '/'
      fullPath: '/$tenant/jobTitles/'
      preLoaderRoute: typeof TenantJobTitlesIndexImport
      parentRoute: typeof TenantJobTitlesRouteLazyImport
    }
    '/$tenant/loans/': {
      id: '/$tenant/loans/'
      path: '/'
      fullPath: '/$tenant/loans/'
      preLoaderRoute: typeof TenantLoansIndexImport
      parentRoute: typeof TenantLoansRouteLazyImport
    }
    '/$tenant/products/': {
      id: '/$tenant/products/'
      path: '/'
      fullPath: '/$tenant/products/'
      preLoaderRoute: typeof TenantProductsIndexImport
      parentRoute: typeof TenantProductsRouteLazyImport
    }
    '/$tenant/roles/': {
      id: '/$tenant/roles/'
      path: '/'
      fullPath: '/$tenant/roles/'
      preLoaderRoute: typeof TenantRolesIndexImport
      parentRoute: typeof TenantRolesRouteLazyImport
    }
    '/$tenant/tenants/': {
      id: '/$tenant/tenants/'
      path: '/'
      fullPath: '/$tenant/tenants/'
      preLoaderRoute: typeof TenantTenantsIndexImport
      parentRoute: typeof TenantTenantsRouteLazyImport
    }
    '/$tenant/users/': {
      id: '/$tenant/users/'
      path: '/'
      fullPath: '/$tenant/users/'
      preLoaderRoute: typeof TenantUsersIndexImport
      parentRoute: typeof TenantUsersRouteLazyImport
    }
    '/$tenant/vendors/': {
      id: '/$tenant/vendors/'
      path: '/'
      fullPath: '/$tenant/vendors/'
      preLoaderRoute: typeof TenantVendorsIndexImport
      parentRoute: typeof TenantVendorsRouteLazyImport
    }
    '/$tenant/employees/pay/$id': {
      id: '/$tenant/employees/pay/$id'
      path: '/pay/$id'
      fullPath: '/$tenant/employees/pay/$id'
      preLoaderRoute: typeof TenantEmployeesPayIdRouteImport
      parentRoute: typeof TenantEmployeesRouteLazyImport
    }
    '/$tenant/loans/pay/$id': {
      id: '/$tenant/loans/pay/$id'
      path: '/pay/$id'
      fullPath: '/$tenant/loans/pay/$id'
      preLoaderRoute: typeof TenantLoansPayIdRouteImport
      parentRoute: typeof TenantLoansRouteLazyImport
    }
    '/$tenant/customers/edit/$id': {
      id: '/$tenant/customers/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/customers/edit/$id'
      preLoaderRoute: typeof TenantCustomersEditIdImport
      parentRoute: typeof TenantCustomersRouteLazyImport
    }
    '/$tenant/departments/edit/$id': {
      id: '/$tenant/departments/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/departments/edit/$id'
      preLoaderRoute: typeof TenantDepartmentsEditIdImport
      parentRoute: typeof TenantDepartmentsRouteLazyImport
    }
    '/$tenant/jobTitles/edit/$id': {
      id: '/$tenant/jobTitles/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/jobTitles/edit/$id'
      preLoaderRoute: typeof TenantJobTitlesEditIdImport
      parentRoute: typeof TenantJobTitlesRouteLazyImport
    }
    '/$tenant/loans/edit/$id': {
      id: '/$tenant/loans/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/loans/edit/$id'
      preLoaderRoute: typeof TenantLoansEditIdImport
      parentRoute: typeof TenantLoansRouteLazyImport
    }
    '/$tenant/products/edit/$id': {
      id: '/$tenant/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/products/edit/$id'
      preLoaderRoute: typeof TenantProductsEditIdImport
      parentRoute: typeof TenantProductsRouteLazyImport
    }
    '/$tenant/roles/edit/$id': {
      id: '/$tenant/roles/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/roles/edit/$id'
      preLoaderRoute: typeof TenantRolesEditIdImport
      parentRoute: typeof TenantRolesRouteLazyImport
    }
    '/$tenant/tenants/edit/$id': {
      id: '/$tenant/tenants/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/tenants/edit/$id'
      preLoaderRoute: typeof TenantTenantsEditIdImport
      parentRoute: typeof TenantTenantsRouteLazyImport
    }
    '/$tenant/users/edit/$id': {
      id: '/$tenant/users/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/users/edit/$id'
      preLoaderRoute: typeof TenantUsersEditIdImport
      parentRoute: typeof TenantUsersRouteLazyImport
    }
    '/$tenant/vendors/edit/$id': {
      id: '/$tenant/vendors/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/vendors/edit/$id'
      preLoaderRoute: typeof TenantVendorsEditIdImport
      parentRoute: typeof TenantVendorsRouteLazyImport
    }
    '/$tenant/employees/edit/$id': {
      id: '/$tenant/employees/edit/$id'
      path: '/edit/$id'
      fullPath: '/$tenant/employees/edit/$id'
      preLoaderRoute: typeof TenantEmployeesEditIdLazyImport
      parentRoute: typeof TenantEmployeesRouteLazyImport
    }
    '/$tenant/employees/pay/$id/add': {
      id: '/$tenant/employees/pay/$id/add'
      path: '/add'
      fullPath: '/$tenant/employees/pay/$id/add'
      preLoaderRoute: typeof TenantEmployeesPayIdAddImport
      parentRoute: typeof TenantEmployeesPayIdRouteImport
    }
    '/$tenant/loans/pay/$id/add': {
      id: '/$tenant/loans/pay/$id/add'
      path: '/add'
      fullPath: '/$tenant/loans/pay/$id/add'
      preLoaderRoute: typeof TenantLoansPayIdAddImport
      parentRoute: typeof TenantLoansPayIdRouteImport
    }
    '/$tenant/loans/pay/$id/edit/$paymentId': {
      id: '/$tenant/loans/pay/$id/edit/$paymentId'
      path: '/edit/$paymentId'
      fullPath: '/$tenant/loans/pay/$id/edit/$paymentId'
      preLoaderRoute: typeof TenantLoansPayIdEditPaymentIdImport
      parentRoute: typeof TenantLoansPayIdRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  RouteRoute,
  TenantRouteLazyRoute: TenantRouteLazyRoute.addChildren({
    TenantCustomersRouteLazyRoute: TenantCustomersRouteLazyRoute.addChildren({
      TenantCustomersIdRoute,
      TenantCustomersAddRoute,
      TenantCustomersIndexRoute,
      TenantCustomersEditIdRoute,
    }),
    TenantDepartmentsRouteLazyRoute:
      TenantDepartmentsRouteLazyRoute.addChildren({
        TenantDepartmentsIdRoute,
        TenantDepartmentsAddRoute,
        TenantDepartmentsIndexRoute,
        TenantDepartmentsEditIdRoute,
      }),
    TenantEmployeesRouteLazyRoute: TenantEmployeesRouteLazyRoute.addChildren({
      TenantEmployeesIdRoute,
      TenantEmployeesAddLazyRoute,
      TenantEmployeesIndexRoute,
      TenantEmployeesPayIdRouteRoute:
        TenantEmployeesPayIdRouteRoute.addChildren({
          TenantEmployeesPayIdAddRoute,
        }),
      TenantEmployeesEditIdLazyRoute,
    }),
    TenantHamadaRouteLazyRoute,
    TenantJobTitlesRouteLazyRoute: TenantJobTitlesRouteLazyRoute.addChildren({
      TenantJobTitlesIdRoute,
      TenantJobTitlesAddRoute,
      TenantJobTitlesIndexRoute,
      TenantJobTitlesEditIdRoute,
    }),
    TenantLoansRouteLazyRoute: TenantLoansRouteLazyRoute.addChildren({
      TenantLoansIdRoute,
      TenantLoansAddRoute,
      TenantLoansIndexRoute,
      TenantLoansPayIdRouteRoute: TenantLoansPayIdRouteRoute.addChildren({
        TenantLoansPayIdAddRoute,
        TenantLoansPayIdEditPaymentIdRoute,
      }),
      TenantLoansEditIdRoute,
    }),
    TenantProductsRouteLazyRoute: TenantProductsRouteLazyRoute.addChildren({
      TenantProductsIdRoute,
      TenantProductsAddRoute,
      TenantProductsIndexRoute,
      TenantProductsEditIdRoute,
    }),
    TenantRolesRouteLazyRoute: TenantRolesRouteLazyRoute.addChildren({
      TenantRolesIdRoute,
      TenantRolesAddRoute,
      TenantRolesIndexRoute,
      TenantRolesEditIdRoute,
    }),
    TenantTenantsRouteLazyRoute: TenantTenantsRouteLazyRoute.addChildren({
      TenantTenantsIdRoute,
      TenantTenantsAddRoute,
      TenantTenantsIndexRoute,
      TenantTenantsEditIdRoute,
    }),
    TenantUsersRouteLazyRoute: TenantUsersRouteLazyRoute.addChildren({
      TenantUsersIdRoute,
      TenantUsersAddRoute,
      TenantUsersApprovedRoute,
      TenantUsersIndexRoute,
      TenantUsersEditIdRoute,
    }),
    TenantVendorsRouteLazyRoute: TenantVendorsRouteLazyRoute.addChildren({
      TenantVendorsIdRoute,
      TenantVendorsAddRoute,
      TenantVendorsIndexRoute,
      TenantVendorsEditIdRoute,
    }),
    TenantIndexRoute,
  }),
  ApprovalRouteLazyRoute,
  LearnMoreRouteLazyRoute,
  AuthLazyRoute: AuthLazyRoute.addChildren({
    AuthCompanySelectRouteLazyRoute,
    AuthForgotPasswordRouteLazyRoute,
    AuthLoginRouteLazyRoute,
    AuthRegisterRouteLazyRoute: AuthRegisterRouteLazyRoute.addChildren({
      AuthRegisterUuidRouteLazyRoute,
    }),
    AuthResetPasswordTokenLazyRoute,
  }),
  AboutLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$tenant",
        "/approval",
        "/learn-more",
        "/_auth",
        "/about"
      ]
    },
    "/": {
      "filePath": "route.tsx"
    },
    "/$tenant": {
      "filePath": "$tenant/route.lazy.tsx",
      "children": [
        "/$tenant/customers",
        "/$tenant/departments",
        "/$tenant/employees",
        "/$tenant/hamada",
        "/$tenant/jobTitles",
        "/$tenant/loans",
        "/$tenant/products",
        "/$tenant/roles",
        "/$tenant/tenants",
        "/$tenant/users",
        "/$tenant/vendors",
        "/$tenant/"
      ]
    },
    "/approval": {
      "filePath": "approval/route.lazy.tsx"
    },
    "/learn-more": {
      "filePath": "learn-more/route.lazy.tsx"
    },
    "/_auth": {
      "filePath": "_auth.lazy.tsx",
      "children": [
        "/_auth/company-select",
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/register",
        "/_auth/reset-password/$token"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/$tenant/customers": {
      "filePath": "$tenant/customers/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/customers/$id",
        "/$tenant/customers/add",
        "/$tenant/customers/",
        "/$tenant/customers/edit/$id"
      ]
    },
    "/$tenant/departments": {
      "filePath": "$tenant/departments/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/departments/$id",
        "/$tenant/departments/add",
        "/$tenant/departments/",
        "/$tenant/departments/edit/$id"
      ]
    },
    "/$tenant/employees": {
      "filePath": "$tenant/employees/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/employees/$id",
        "/$tenant/employees/add",
        "/$tenant/employees/",
        "/$tenant/employees/pay/$id",
        "/$tenant/employees/edit/$id"
      ]
    },
    "/$tenant/hamada": {
      "filePath": "$tenant/hamada/route.lazy.tsx",
      "parent": "/$tenant"
    },
    "/$tenant/jobTitles": {
      "filePath": "$tenant/jobTitles/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/jobTitles/$id",
        "/$tenant/jobTitles/add",
        "/$tenant/jobTitles/",
        "/$tenant/jobTitles/edit/$id"
      ]
    },
    "/$tenant/loans": {
      "filePath": "$tenant/loans/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/loans/$id",
        "/$tenant/loans/add",
        "/$tenant/loans/",
        "/$tenant/loans/pay/$id",
        "/$tenant/loans/edit/$id"
      ]
    },
    "/$tenant/products": {
      "filePath": "$tenant/products/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/products/$id",
        "/$tenant/products/add",
        "/$tenant/products/",
        "/$tenant/products/edit/$id"
      ]
    },
    "/$tenant/roles": {
      "filePath": "$tenant/roles/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/roles/$id",
        "/$tenant/roles/add",
        "/$tenant/roles/",
        "/$tenant/roles/edit/$id"
      ]
    },
    "/$tenant/tenants": {
      "filePath": "$tenant/tenants/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/tenants/$id",
        "/$tenant/tenants/add",
        "/$tenant/tenants/",
        "/$tenant/tenants/edit/$id"
      ]
    },
    "/$tenant/users": {
      "filePath": "$tenant/users/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/users/$id",
        "/$tenant/users/add",
        "/$tenant/users/approved",
        "/$tenant/users/",
        "/$tenant/users/edit/$id"
      ]
    },
    "/$tenant/vendors": {
      "filePath": "$tenant/vendors/route.lazy.tsx",
      "parent": "/$tenant",
      "children": [
        "/$tenant/vendors/$id",
        "/$tenant/vendors/add",
        "/$tenant/vendors/",
        "/$tenant/vendors/edit/$id"
      ]
    },
    "/_auth/company-select": {
      "filePath": "_auth/company-select/route.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password/route.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login/route.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register/route.lazy.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/register/$uuid"
      ]
    },
    "/$tenant/": {
      "filePath": "$tenant/index.tsx",
      "parent": "/$tenant"
    },
    "/$tenant/customers/$id": {
      "filePath": "$tenant/customers/$id.tsx",
      "parent": "/$tenant/customers"
    },
    "/$tenant/customers/add": {
      "filePath": "$tenant/customers/add.tsx",
      "parent": "/$tenant/customers"
    },
    "/$tenant/departments/$id": {
      "filePath": "$tenant/departments/$id.tsx",
      "parent": "/$tenant/departments"
    },
    "/$tenant/departments/add": {
      "filePath": "$tenant/departments/add.tsx",
      "parent": "/$tenant/departments"
    },
    "/$tenant/employees/$id": {
      "filePath": "$tenant/employees/$id.tsx",
      "parent": "/$tenant/employees"
    },
    "/$tenant/jobTitles/$id": {
      "filePath": "$tenant/jobTitles/$id.tsx",
      "parent": "/$tenant/jobTitles"
    },
    "/$tenant/jobTitles/add": {
      "filePath": "$tenant/jobTitles/add.tsx",
      "parent": "/$tenant/jobTitles"
    },
    "/$tenant/loans/$id": {
      "filePath": "$tenant/loans/$id.tsx",
      "parent": "/$tenant/loans"
    },
    "/$tenant/loans/add": {
      "filePath": "$tenant/loans/add.tsx",
      "parent": "/$tenant/loans"
    },
    "/$tenant/products/$id": {
      "filePath": "$tenant/products/$id.tsx",
      "parent": "/$tenant/products"
    },
    "/$tenant/products/add": {
      "filePath": "$tenant/products/add.tsx",
      "parent": "/$tenant/products"
    },
    "/$tenant/roles/$id": {
      "filePath": "$tenant/roles/$id.tsx",
      "parent": "/$tenant/roles"
    },
    "/$tenant/roles/add": {
      "filePath": "$tenant/roles/add.tsx",
      "parent": "/$tenant/roles"
    },
    "/$tenant/tenants/$id": {
      "filePath": "$tenant/tenants/$id.tsx",
      "parent": "/$tenant/tenants"
    },
    "/$tenant/tenants/add": {
      "filePath": "$tenant/tenants/add.tsx",
      "parent": "/$tenant/tenants"
    },
    "/$tenant/users/$id": {
      "filePath": "$tenant/users/$id.tsx",
      "parent": "/$tenant/users"
    },
    "/$tenant/users/add": {
      "filePath": "$tenant/users/add.tsx",
      "parent": "/$tenant/users"
    },
    "/$tenant/users/approved": {
      "filePath": "$tenant/users/approved.tsx",
      "parent": "/$tenant/users"
    },
    "/$tenant/vendors/$id": {
      "filePath": "$tenant/vendors/$id.tsx",
      "parent": "/$tenant/vendors"
    },
    "/$tenant/vendors/add": {
      "filePath": "$tenant/vendors/add.tsx",
      "parent": "/$tenant/vendors"
    },
    "/_auth/register/$uuid": {
      "filePath": "_auth/register/$uuid/route.lazy.tsx",
      "parent": "/_auth/register"
    },
    "/$tenant/employees/add": {
      "filePath": "$tenant/employees/add.lazy.tsx",
      "parent": "/$tenant/employees"
    },
    "/_auth/reset-password/$token": {
      "filePath": "_auth/reset-password/$token.lazy.tsx",
      "parent": "/_auth"
    },
    "/$tenant/customers/": {
      "filePath": "$tenant/customers/index.tsx",
      "parent": "/$tenant/customers"
    },
    "/$tenant/departments/": {
      "filePath": "$tenant/departments/index.tsx",
      "parent": "/$tenant/departments"
    },
    "/$tenant/employees/": {
      "filePath": "$tenant/employees/index.tsx",
      "parent": "/$tenant/employees"
    },
    "/$tenant/jobTitles/": {
      "filePath": "$tenant/jobTitles/index.tsx",
      "parent": "/$tenant/jobTitles"
    },
    "/$tenant/loans/": {
      "filePath": "$tenant/loans/index.tsx",
      "parent": "/$tenant/loans"
    },
    "/$tenant/products/": {
      "filePath": "$tenant/products/index.tsx",
      "parent": "/$tenant/products"
    },
    "/$tenant/roles/": {
      "filePath": "$tenant/roles/index.tsx",
      "parent": "/$tenant/roles"
    },
    "/$tenant/tenants/": {
      "filePath": "$tenant/tenants/index.tsx",
      "parent": "/$tenant/tenants"
    },
    "/$tenant/users/": {
      "filePath": "$tenant/users/index.tsx",
      "parent": "/$tenant/users"
    },
    "/$tenant/vendors/": {
      "filePath": "$tenant/vendors/index.tsx",
      "parent": "/$tenant/vendors"
    },
    "/$tenant/employees/pay/$id": {
      "filePath": "$tenant/employees/pay/$id/route.tsx",
      "parent": "/$tenant/employees",
      "children": [
        "/$tenant/employees/pay/$id/add"
      ]
    },
    "/$tenant/loans/pay/$id": {
      "filePath": "$tenant/loans/pay/$id/route.tsx",
      "parent": "/$tenant/loans",
      "children": [
        "/$tenant/loans/pay/$id/add",
        "/$tenant/loans/pay/$id/edit/$paymentId"
      ]
    },
    "/$tenant/customers/edit/$id": {
      "filePath": "$tenant/customers/edit.$id.tsx",
      "parent": "/$tenant/customers"
    },
    "/$tenant/departments/edit/$id": {
      "filePath": "$tenant/departments/edit.$id.tsx",
      "parent": "/$tenant/departments"
    },
    "/$tenant/jobTitles/edit/$id": {
      "filePath": "$tenant/jobTitles/edit.$id.tsx",
      "parent": "/$tenant/jobTitles"
    },
    "/$tenant/loans/edit/$id": {
      "filePath": "$tenant/loans/edit.$id.tsx",
      "parent": "/$tenant/loans"
    },
    "/$tenant/products/edit/$id": {
      "filePath": "$tenant/products/edit.$id.tsx",
      "parent": "/$tenant/products"
    },
    "/$tenant/roles/edit/$id": {
      "filePath": "$tenant/roles/edit.$id.tsx",
      "parent": "/$tenant/roles"
    },
    "/$tenant/tenants/edit/$id": {
      "filePath": "$tenant/tenants/edit.$id.tsx",
      "parent": "/$tenant/tenants"
    },
    "/$tenant/users/edit/$id": {
      "filePath": "$tenant/users/edit.$id.tsx",
      "parent": "/$tenant/users"
    },
    "/$tenant/vendors/edit/$id": {
      "filePath": "$tenant/vendors/edit.$id.tsx",
      "parent": "/$tenant/vendors"
    },
    "/$tenant/employees/edit/$id": {
      "filePath": "$tenant/employees/edit.$id.lazy.tsx",
      "parent": "/$tenant/employees"
    },
    "/$tenant/employees/pay/$id/add": {
      "filePath": "$tenant/employees/pay/$id/add.tsx",
      "parent": "/$tenant/employees/pay/$id"
    },
    "/$tenant/loans/pay/$id/add": {
      "filePath": "$tenant/loans/pay/$id/add.tsx",
      "parent": "/$tenant/loans/pay/$id"
    },
    "/$tenant/loans/pay/$id/edit/$paymentId": {
      "filePath": "$tenant/loans/pay/$id/edit.$paymentId.tsx",
      "parent": "/$tenant/loans/pay/$id"
    }
  }
}
ROUTE_MANIFEST_END */
